stages:
  - building

build images:
  image: docker/compose:1.27.2
  services:
    - docker:18.09.7-dind
  stage: building
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker-compose build --compress --force-rm --pull
    - docker-compose push
  only:
    - master
    - schedules
    - tags
